### PR TITLE
B 155 fix

### PR DESCRIPTION
**Pull request by baxterjfinch**

### CODE REVIEW

**Comment by izelnakri** [comment]
Hi @baxterjfinch , have you run the tests? Our CI was broken so I merged the PR, however I just realized locally tests are failing, I cant cut a release without fixing the test suite. Please create another PR with test suite fixes, then we can cut a release. You can run the test suite by: `$ mix test --seed 0` Thanks.

**Comment by baxterjfinch** [comment]
Hello @izelnakri , thanks! I'll take a look at the tests today. I'm still not sure that the `v` value is being constructed correctly. Have you been able to send transactions that are EIP-155 compliant? 

A transaction we have used to test still comes back with a `v` value of 28:
https://www.ethereumdecoder.com/?search=0xb1b0a25362b65e9fef96fb09c9cbffc9993a0ed5ab66adbbd2895c632d67c402

We use Alchemy as our provider and they are not going to allow non-compliant EIP-155 transactions soon so we're hoping to get a fix into this library soon. Thanks! :)

**Comment by albertoramires** [comment]
@izelnakri @baxterjfinch is this working for anything other than 0-9 chain ids? If I use Optimism Goerli `<<chain_id_int>> = chain_id` won't match. 🤔

**Comment by izelnakri** [comment]
@albertoramires ETH provides no guarantee or promises at this point, we dont even have a working test suite now for a while. My time needs to be managed properly. Please read the code and contribute to project if it isn't serve your needs at this point. Thanks!

**Comment by albertoramires** [comment]
@izelnakri no worries, was making sure it wasn't just an issue on my side. Thank you.

**Pull request merged**
